apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-cluster-manager
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["namespaces", "deployments", "replicasets", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

