apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - name: html-generator              # Contaienr này thay đổi dữ liệu trong volume chung
      image: luksa/fortune
      volumeMounts:
        - name: html        # Mount volume vào thư mục /var/htdocs trong container 
          mountPath: /var/htdocs
    - name: web-server                   # container này đọc dữ liệu volume chung hiển thị thành web
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html #  mount volume  html vào thư mục /usr/share/nginx/html bên trong container
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:   #              định nghĩa volumes
    - name: html  #           đặt tên volumes
      emptyDir: {}   #       định nghĩa kiểu volume là emptyDir
