apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: nfsstorageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/mydata/"
    server: "10.0.5.80"       # đây là IP của EC2 CentOS NFS
